### ISSUE TITLE
position of the title

### ISSUE THREAD

**Issue by kelalaka153** [androidseb/android-google-maps-floating-marker-titles#2]
Is it possible to place title position as in Goolge maps or at top of the icon? I've tried to modify 

`(float) newLocation.y - currentArea.height() / 2,
`
to 
`(float) newLocation.y - 20 - currentArea.height() / 2,
`
from updateCurrentlyDisplayedMarkers(.. ) but the text flied up.

**Comment by androidseb** [comment]
If you want to center the title on top of the marker, assuming your marker icon is 48 dip high, you should replace
```
currentArea.set(//
	(float) newLocation.x + textPaddingToMarker,//
	(float) newLocation.y - currentArea.height() / 2,//
	(float) newLocation.x + textPaddingToMarker + currentArea.width(),//
	(float) newLocation.y + currentArea.height() / 2//
);
```
With
```
float yOffset = GMFMTUtils.dipToPixels(getContext(), 48);
currentArea.set(//
	(float) newLocation.x - currentArea.width() / 2,//
	(float) newLocation.y - yOffset - currentArea.height(),//
	(float) newLocation.x + currentArea.width() / 2,//
	(float) newLocation.y - yOffset//
);
```
I hope this helps!

**Comment by androidseb** [comment]
Hey, closing this issue now, I think this solved your problem. Feel free to re-open otherwise :-)
